# Generated by Django 3.0.6 on 2020-05-29 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_art',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('content', models.TextField(max_length=65535)),
                ('index', models.IntegerField()),
                ('book_id', models.IntegerField(null=True)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('com_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pic', models.FileField(default='/book/default.png', upload_to='book/')),
                ('coll_num', models.IntegerField()),
                ('like_num', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_art')),
            ],
        ),
        migrations.CreateModel(
            name='t_register_cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255, null=True)),
                ('random', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(max_length=32, null=True, unique=True)),
                ('pwd', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('avatar', models.FileField(default='/avatar/default.png', upload_to='avatar/')),
                ('Intro', models.CharField(default='', max_length=255)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_user_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='u1', to='FictionRead.t_user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='u2', to='FictionRead.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_pri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show_info', models.BooleanField(default=True)),
                ('is_show_coll', models.BooleanField(default=True)),
                ('is_show_like', models.BooleanField(default=True)),
                ('is_show_sub', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_cre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_com',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('anc_com', models.IntegerField(null=True)),
                ('rep_user', models.IntegerField(null=True)),
                ('content', models.CharField(max_length=255)),
                ('like_num', models.IntegerField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commenter', to='FictionRead.t_user')),
            ],
        ),
        migrations.CreateModel(
            name='t_coll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FictionRead.t_user')),
            ],
        ),
    ]
